apiVersion: v1
kind: Service
metadata:
  labels:
    name: mywebapp
  name: mywebapp
spec:
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
  selector:
    name: mywebapp
  type: NodePort
  #type: LoadBalancer